# Generated by Django 5.2.7 on 2025-10-13 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('file', models.FileField(upload_to='documenti/')),
                ('categoria', models.CharField(max_length=100)),
                ('data_pubblicazione', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Documenti Informativi',
                'ordering': ['-data_pubblicazione'],
            },
        ),
        migrations.CreateModel(
            name='Filiale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Santander Filiale', max_length=200)),
                ('indirizzo', models.CharField(max_length=300)),
                ('citta', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('orario_apertura', models.TextField(help_text='Orari di apertura')),
                ('descrizione', models.TextField()),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='filiale/')),
            ],
            options={
                'verbose_name_plural': 'Filiali',
            },
        ),
        migrations.CreateModel(
            name='RichiestaContatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('motivo', models.CharField(choices=[('info_prestito', 'Informazioni su Prestito'), ('info_mutuo', 'Informazioni su Mutuo'), ('appuntamento', 'Richiesta Appuntamento'), ('reclamo', 'Reclamo'), ('altro', 'Altro')], max_length=50)),
                ('messaggio', models.TextField()),
                ('privacy_accettata', models.BooleanField(default=False)),
                ('data_richiesta', models.DateTimeField(auto_now_add=True)),
                ('gestita', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Richieste di Contatto',
                'ordering': ['-data_richiesta'],
            },
        ),
        migrations.CreateModel(
            name='TipoPrestito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('personale', 'Prestito Personale'), ('auto', 'Prestito Auto'), ('casa', 'Mutuo Casa'), ('ristrutturazione', 'Prestito Ristrutturazione'), ('liquidita', 'Prestito Liquidità')], max_length=50)),
                ('descrizione_breve', models.CharField(max_length=300)),
                ('descrizione_completa', models.TextField()),
                ('tasso_interesse_da', models.DecimalField(decimal_places=2, help_text='Tasso di interesse minimo (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('importo_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importo_massimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('durata_mesi_min', models.IntegerField(help_text='Durata minima in mesi')),
                ('durata_mesi_max', models.IntegerField(help_text='Durata massima in mesi')),
                ('vantaggi', models.TextField(help_text='Elenco vantaggi (uno per riga)')),
                ('requisiti', models.TextField(help_text='Requisiti necessari')),
                ('icona', models.CharField(blank=True, help_text='Classe icona CSS', max_length=50)),
                ('attivo', models.BooleanField(default=True)),
                ('ordine', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Tipi di Prestito',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('iniziale_cognome', models.CharField(help_text='Es: M.', max_length=1)),
                ('testimonianza', models.TextField()),
                ('valutazione', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('data_pubblicazione', models.DateField(auto_now_add=True)),
                ('approvato', models.BooleanField(default=False)),
                ('tipo_servizio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiale.tipoprestito')),
            ],
            options={
                'verbose_name_plural': 'Testimonial',
                'ordering': ['-data_pubblicazione'],
            },
        ),
    ]
