# Generated by Django 5.2.7 on 2025-10-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiestacontatto',
            name='motivo',
            field=models.CharField(choices=[('info_prestito', 'Informazioni su Prestito'), ('info_mutuo', 'Informazioni su Mutuo'), ('appuntamento', 'Richiesta Appuntamento'), ('reclamo', 'Reclamo'), ('PREV', 'Richiesta di Preventivo'), ('altro', 'Altro')], default='altro', max_length=50),
        ),
    ]
