# Generated by Django 5.2.7 on 2025-10-15 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiale', '0002_alter_richiestacontatto_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appuntamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.DateField()),
                ('ora', models.TimeField()),
                ('data_prenotazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('motivo', models.TextField(max_length=500, verbose_name="Motivo dell'Appuntamento")),
            ],
            options={
                'verbose_name_plural': 'Appuntamenti',
                'ordering': ['giorno', 'ora'],
                'unique_together': {('giorno', 'ora')},
            },
        ),
    ]
